# Makefile
help:
	@echo "Usage: `make deploy` to deploy the policy"
deploy:
	cp -f $(CURDIR)/final.zip ../../../data/params.zip
	cp -f $(CURDIR)/operative_config.gin ../../../data/operative_config.gin